// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// ziTobitBayesQR
List ziTobitBayesQR(double tau, arma::colvec y, arma::mat X, int itNum, int thin, arma::colvec betaValue, double sigmaValue, arma::colvec betaZeroValue, double sigmaBetaZero, int link);
RcppExport SEXP baquantreg_ziTobitBayesQR(SEXP tauSEXP, SEXP ySEXP, SEXP XSEXP, SEXP itNumSEXP, SEXP thinSEXP, SEXP betaValueSEXP, SEXP sigmaValueSEXP, SEXP betaZeroValueSEXP, SEXP sigmaBetaZeroSEXP, SEXP linkSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type itNum(itNumSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type betaValue(betaValueSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaValue(sigmaValueSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type betaZeroValue(betaZeroValueSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaBetaZero(sigmaBetaZeroSEXP);
    Rcpp::traits::input_parameter< int >::type link(linkSEXP);
    __result = Rcpp::wrap(ziTobitBayesQR(tau, y, X, itNum, thin, betaValue, sigmaValue, betaZeroValue, sigmaBetaZero, link));
    return __result;
END_RCPP
}
