# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ziTobitBayesQR <- function(tau, y, X, itNum, thin, betaValue, sigmaValue, gammaValue, sigmaGamma, link) {
    .Call('baquantreg_ziTobitBayesQR', PACKAGE = 'baquantreg', tau, y, X, itNum, thin, betaValue, sigmaValue, gammaValue, sigmaGamma, link)
}

