# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BayesQR <- function(tau, y, X, itNum, thin, betaValue, sigmaValue, vSampleInit, priorVar, hyperSigma, refresh, sigmaSampling, quiet, tobit, recordLat, blocksV, stopOrdering, numOrdered) {
    .Call('_baquantreg_BayesQR', PACKAGE = 'baquantreg', tau, y, X, itNum, thin, betaValue, sigmaValue, vSampleInit, priorVar, hyperSigma, refresh, sigmaSampling, quiet, tobit, recordLat, blocksV, stopOrdering, numOrdered)
}

tpBayesQR <- function(tau, y, X, itNum, thin, betaValue, sigmaValue, vSampleInit, gammaValue, sigmaGamma, link, priorVar, refresh, quiet) {
    .Call('_baquantreg_tpBayesQR', PACKAGE = 'baquantreg', tau, y, X, itNum, thin, betaValue, sigmaValue, vSampleInit, gammaValue, sigmaGamma, link, priorVar, refresh, quiet)
}

ziTobitBayesQR <- function(tau, y, X, itNum, thin, betaValue, sigmaValue, gammaValue, sigmaGamma, link, priorVar, refresh, quiet, burnin) {
    .Call('_baquantreg_ziTobitBayesQR', PACKAGE = 'baquantreg', tau, y, X, itNum, thin, betaValue, sigmaValue, gammaValue, sigmaGamma, link, priorVar, refresh, quiet, burnin)
}

checkPoints <- function(gridy1, gridy2, directions, orthBasis, fullestimates, xvalue, splines, addterm) {
    .Call('_baquantreg_checkPoints', PACKAGE = 'baquantreg', gridy1, gridy2, directions, orthBasis, fullestimates, xvalue, splines, addterm)
}

rgigRcpp <- function(chi, psi, lambda) {
    .Call('_baquantreg_rgigRcpp', PACKAGE = 'baquantreg', chi, psi, lambda)
}

spBayesQR <- function(tau, y, X, itNum, thin, betaValue, sigmaValue, matDist, lambda, tuneP, alphaValue, tuneA, priorVar, refresh, quiet, jitter, includeAlpha, tuneV, kMT, shapeL, rateL) {
    .Call('_baquantreg_spBayesQR', PACKAGE = 'baquantreg', tau, y, X, itNum, thin, betaValue, sigmaValue, matDist, lambda, tuneP, alphaValue, tuneA, priorVar, refresh, quiet, jitter, includeAlpha, tuneV, kMT, shapeL, rateL)
}

sppBayesQR <- function(tau, y, X, itNum, thin, betaValue, sigmaValue, matDist, lambdaVec, lambda, shapeL, rateL, tuneP, indices, m, alphaValue, tuneA, priorVar, quiet, refresh, jitter, includeAlpha, tuneV, kMT, discLambda) {
    .Call('_baquantreg_sppBayesQR', PACKAGE = 'baquantreg', tau, y, X, itNum, thin, betaValue, sigmaValue, matDist, lambdaVec, lambda, shapeL, rateL, tuneP, indices, m, alphaValue, tuneA, priorVar, quiet, refresh, jitter, includeAlpha, tuneV, kMT, discLambda)
}

