# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BayesQR <- function(tau, y, X, itNum, thin, betaValue, sigmaValue, vSampleInit, priorVar, refresh, quiet, tobit) {
    .Call('baquantreg_BayesQR', PACKAGE = 'baquantreg', tau, y, X, itNum, thin, betaValue, sigmaValue, vSampleInit, priorVar, refresh, quiet, tobit)
}

tpBayesQR <- function(tau, y, X, itNum, thin, betaValue, sigmaValue, vSampleInit, gammaValue, sigmaGamma, link, priorVar, refresh, quiet) {
    .Call('baquantreg_tpBayesQR', PACKAGE = 'baquantreg', tau, y, X, itNum, thin, betaValue, sigmaValue, vSampleInit, gammaValue, sigmaGamma, link, priorVar, refresh, quiet)
}

ziTobitBayesQR <- function(tau, y, X, itNum, thin, betaValue, sigmaValue, gammaValue, sigmaGamma, link, priorVar, refresh, quiet, burnin) {
    .Call('baquantreg_ziTobitBayesQR', PACKAGE = 'baquantreg', tau, y, X, itNum, thin, betaValue, sigmaValue, gammaValue, sigmaGamma, link, priorVar, refresh, quiet, burnin)
}

rgigRcpp <- function(chi, psi, lambda) {
    .Call('baquantreg_rgigRcpp', PACKAGE = 'baquantreg', chi, psi, lambda)
}

spBayesQR <- function(tau, y, X, itNum, thin, betaValue, sigmaValue, matDist, lambda, tuneP, alphaValue, tuneA, priorVar, refresh, quiet, jitter, includeAlpha, tuneV, kMT, shapeL, rateL) {
    .Call('baquantreg_spBayesQR', PACKAGE = 'baquantreg', tau, y, X, itNum, thin, betaValue, sigmaValue, matDist, lambda, tuneP, alphaValue, tuneA, priorVar, refresh, quiet, jitter, includeAlpha, tuneV, kMT, shapeL, rateL)
}

sppBayesQR <- function(tau, y, X, itNum, thin, betaValue, sigmaValue, matDist, lambdaVec, lambda, shapeL, rateL, tuneP, indices, m, alphaValue, tuneA, priorVar, quiet, refresh, jitter, includeAlpha, tuneV, kMT, discLambda) {
    .Call('baquantreg_sppBayesQR', PACKAGE = 'baquantreg', tau, y, X, itNum, thin, betaValue, sigmaValue, matDist, lambdaVec, lambda, shapeL, rateL, tuneP, indices, m, alphaValue, tuneA, priorVar, quiet, refresh, jitter, includeAlpha, tuneV, kMT, discLambda)
}

